version: "3.7"
networks:
  mynet:
    driver: overlay
configs:
  haproxy-cfg:
    file: haproxy.cfg    
volumes:
  mysql-data:
services:
  php:
    image: myapp:1
    ports:
      - 7070:80        
    deploy:
      mode: global
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first      
    networks:
      - mynet
  db:
    image: mysql:5.6
    env_file:
      - ./.env
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 3
      placement:
         constraints:
            - node.role == manager
    networks:
      - mynet      
  proxy:
    image: haproxy
    ports:     
      - 80:80 # Roundrobin
      - 9001:9000 # Haproxy Stats
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == jagan
    networks:
      - mynet
    configs:
      - source: haproxy-cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
