version: "3.7"
configs:
  haproxy-cfg:
    file: ./haproxy/haproxy.cfg
services:
  db:
    image: mysql:5.6
    env_file:
      - ./env/.env
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == node1
    networks:
      - mynet
  web:
    image: apache-php-mysql:1
    ports:
      - 7000:80        
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == manager   
    depends_on:
      - db
    networks:
      - mynet
  haproxy:
    image: haproxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
           - node.role == manager
    ports:
      - 80:80 # Roundrobin
      - 9000:9000 # #Haproxy Stats
    networks:
      - mynet
    configs:
      - source: haproxy-cfg
        target: /usr/local/etc/haproxy/haproxy.cfg    
networks:
  mynet:
    driver: overlay
volumes:    
  mysql-data:
